server:
  port: 8082

spring:
  application:
    name: catalog-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5433/catalog_db}
    username: ${SPRING_R2DBC_USERNAME:catalog_admin}
    password: ${SPRING_R2DBC_PASSWORD:password123}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
