steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/api-gateway:$COMMIT_SHA', '-f', 'api-gateway/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/api-gateway:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-gateway'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/api-gateway:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # ESTE SÍ PERMITE TRÁFICO DE INTERNET
      - '--set-env-vars'
      - 'USERS_SERVICE_URL=$_USERS_URL,INVENTORY_SERVICE_URL=$_INVENTORY_URL'