steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/catalog-service:$COMMIT_SHA', '-f', 'catalog-service/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/catalog-service:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'catalog-service'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/catalog-service:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--network'
      - 'default'
      - '--set-env-vars'
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://$_DB_IP:5432/catalog_db,SPRING_R2DBC_USERNAME=$_DB_USER,SPRING_R2DBC_PASSWORD=$_DB_PASS'
