steps:
  # 1. Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA', '-f', 'users-service/Dockerfile', '.']

  # 2. Subir a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA']

  # 3. Desplegar en Cloud Run (Privado)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'users-service'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/users-service:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Bloquea acceso público
      - '--network' # Habilita conexión a VPC para BD Privada
      - 'default'
      - '--set-env-vars'
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://$_DB_IP:5432/users_db,SPRING_R2DBC_USERNAME=$_DB_USER,SPRING_R2DBC_PASSWORD=$_DB_PASS'