server:
  port: 8081

spring:
  application:
    name: users-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/users_db}
    username: ${SPRING_R2DBC_USERNAME:user_admin}
    password: ${SPRING_R2DBC_PASSWORD:password123}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

jwt:
  secret: ${JWT_SECRET:MiSuperSecretoJWTKey1234567890MiSuperSecretoJWTKey1234567890!}
  expiration: 86400000 # 24 horas en ms
