server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://sistema-de-inventario-2e3c2.web.app"
              - "https://sistema-de-inventario-2e3c2.firebaseapp.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**
        - id: catalog-read-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/catalog/**
          filters:
            - JwtAuthFilter
            - RoleAuthFilter=ADMIN,USER
        - id: catalog-write-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/catalog/**
          filters:
            - JwtAuthFilter
            - RoleAuthFilter=ADMIN
        - id: inventory-read-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/reports/**
          filters:
            - JwtAuthFilter
            - RoleAuthFilter=ADMIN,USER
        - id: inventory-write-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/inventory/**
          filters:
            - JwtAuthFilter
            - RoleAuthFilter=ADMIN
        - id: sales-read-service
          uri: ${SALES_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/sales/**
          filters:
            - JwtAuthFilter
            - RoleAuthFilter=ADMIN,USER
        - id: sales-write-service
          uri: ${SALES_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/sales/**
          filters:
            - JwtAuthFilter
            - RoleAuthFilter=ADMIN,USER

jwt:
  secret: ${JWT_SECRET:MiSuperSecretoJWTKey1234567890MiSuperSecretoJWTKey1234567890!}
