server:
  port: 8086

spring:
  application:
    name: sales-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5437/sales_db}
    username: ${SPRING_R2DBC_USERNAME:sales_admin}
    password: ${SPRING_R2DBC_PASSWORD:password123}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
